config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  #resources :users do 
    
  #end
  resources :leave_requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_for :admins, ActiveAdmin::Devise.config

  # below code to fix the active admin issue when table not exists in database as activeadmin tries to load every model.
  # for reference https://github.com/activeadmin/activeadmin/issues/783
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'

end

app/models/admin.rb
class Admin < Patron

  def decrement_invitation_limit!
    #stub functionality because devise invitation call this method to decrement the counter.
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave_request.rb
class LeaveRequest < ApplicationRecord
	belongs_to :patron
	validates_presence_of :commence, :end_date, :reason

	scope :pending_approval, -> { where(status: 0) }


	enum status: {pending: 0, approved: 1, rejected: 2 } do
	    event :approve do
  		after do
        	LeaveMailer.notify_user(self.patron.id, self.id).deliver_later
      	end
	      transition [:pending, :rejected] => :approved
	    end

	    event :reject do
  		after do
        	LeaveMailer.notify_user(self.patron.id, self.id).deliver_later
      	end
	      transition [:pending, :approved] => :rejected
	    end
	end
end

app/models/patron.rb
class Patron < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # self.abstract_class = true
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :leave_requests

  def send_devise_notification(notification, *args)
  	devise_mailer.send(notification, self, *args).deliver_later
  end

end

app/models/user.rb
class User < Patron
  devise :invitable, :registerable, :confirmable

  def full_name
  	"#{first_name.humanize} #{last_name.humanize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :redirect_url

  def redirect_url
    return new_patron_session_path unless patron_signed_in?
    case current_patron
      when User
        root_path
      when Admin
        root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  	@leave_requests = current_user.leave_requests.order('created_at DESC')
  end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < InheritedResources::Base

  def new
    @leave_request = LeaveRequest.new
  end
  
  def create 
     @leave_request = current_user.leave_requests.build(leave_request_params)
      if @leave_request.save
        flash[:notice] = "Your leave request has been submitted to be approved"
        redirect_to root_url
      else
        flash[:notice] = "There was an error submitting your leave request"
        render :action => :new
      end
  end

  def index
  	@leave_requests = LeaveRequest.all.where("end_date >= ? and status = ?", Date.today, 1)
  end


  private

    def leave_request_params
      params.require(:leave_request).permit(:commence, :end_date, :reason)
    end
end

app/controllers/sessions_controller.rb
# class SessionsController < ApplicationController
#
#   def after_sign_in_path_for(resource)
#     stored_location_for(resource) || redirect_url
#   end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end
end

app/helpers/devise_bootstrap_errors_helper.rb
module DeviseBootstrapErrorsHelper
  def devise_bootstrap_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block devise-bs">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h5>#{sentence}</h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-12 text-xs-center bootstrap-welcome">
    <h3 class="section-title text-center m-5">Welcome back <%= current_user.email %></h3>

    <div class="col-md-10 ml-auto mr-auto">
    	<h3 class="mb-4">Leave Requests</h3>
    	<div class="table-responsive">
			<table class="table table-striped">
			  <thead>
			    <tr>
			      <th>Commence</th>
			      <th>End</th>
			      <th>Reason</th>
			      <th>Approval Status</th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @leave_requests.each do |leave_request| %>
			      <tr>
			        <td><%= leave_request.commence.strftime("%A, %B %d, %Y") %></td>
			        <td><%= leave_request.end_date.strftime("%A, %B %d, %Y") %></td>
			        <td><%= leave_request.reason %></td>
			        <td><%= leave_request.status %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>OOZ Leave Request Application</title>
        <meta name="description" content="A Leave Request Application for SMEs and Charities">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS Dependencies -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body class="shards-app-promo-page--1">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <a class="navbar-brand mr-5" href="/">
          <%= image_tag "ooz_logo.png", class: "mr-2", alt: "OOZ Leave Request App" %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, :class => "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Admin', new_admin_session_path, :class => "nav-link" %>
            </li>

            <% if current_user %>
              <li class="nav-item">
                <%= link_to 'Who\'s off?', leave_requests_path , :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Create Leave Request', new_leave_request_path , :class => "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Edit Profile', edit_user_registration_path(current_user), :class => "nav-link" %>
              </li>
              <li class="nav-item">          
                <%= link_to 'Logout', eval("destroy_#{current_user.type.downcase}_session_path"), method: :delete, :class => "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <div class="section-invert py-4">
        <div class="row">
          <div class="col-sm-12 text-xs-center bootstrap-welcome">
            <%= render partial: 'shared/flash' unless flash.empty? %>
            <%= yield %>
          </div>
        </div>
      </div>
      <!-- Footer Section -->
    <footer class="main-footer py-5">
      <p class="text-muted text-center small p-0 mb-4">© Copyright 2019 — Leave Request Application designed by <a href="http://www.thoughtstudiosng.com">ThoughtStudios Limited.</a></p>
    </footer>
      <!-- / Footer Section -->

      <!-- JavaScript Dependencies -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

app/views/leave_requests/_form.html.erb
<div class="col-lg-8 col-md-10 ml-auto mr-auto">
  <div class="row mb-5">
    <div class="col-md-12">
      <%= form_for(leave_request) do |f| %>
        <% if leave_request.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(leave_request.errors.count, "error") %> prohibited this leave_request from being saved:</h2>

            <ul>
            <% leave_request.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="form-group col-md-6">
            <%= f.label :commence, class: "col-form-label" %>
            <div class="input-group with-addon-icon-left">
              <%= f.text_field :commence, class: "form-control input-sm", 'data-provide': "datepicker",'data-date-format': "dd/mm/yyyy" %>
              <span class="input-group-append">
                <span class="input-group-text">
                    <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :end_date, class: "col-form-label" %>
            <div class="input-group with-addon-icon-left">
              <%= f.text_field :end_date, class: "form-control input-sm", 'data-provide': "datepicker",'data-date-format': "dd/mm/yyyy" %>
              <span class="input-group-append">
                <span class="input-group-text">
                    <i class="fa fa-calendar"></i>
                </span>
              </span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-12">
            <%= f.label :reason, class: "col-form-label" %>
            <%= f.text_area :reason, class: "form-control" %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit nil, :class => 'btn btn-primary btn-lg d-table ml-auto mr-auto' %>
        </div>

      <% end %>

      <%= link_to 'Back', leave_requests_path, :class => 'btn btn-danger'%>
    </div>
  </div>
</div>

app/views/leave_requests/edit.html.erb
<h3 class="section-title text-center m-5">Editing Leave Request</h3>

<%= render 'form', leave_request: @leave_request %>

app/views/leave_requests/index.html.erb
<h3 class="section-title text-center m-5">Leave Requests</h3>
  <p id="notice"><%= notice %></p>
  <div class="col-md-10 ml-auto mr-auto">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>

        <tbody>
          <% @leave_requests.each do |leave_request| %>
            <tr>
              <td><%= leave_request.patron.first_name %></td>
              <td><%= leave_request.patron.last_name %></td>
              <td><%= leave_request.commence.strftime("%A, %B %d, %Y") %></td>
              <td><%= leave_request.end_date.strftime("%A, %B %d, %Y") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New Leave Request', new_leave_request_path, :class => 'btn btn-primary btn-lg d-table ml-auto mr-auto' %>
  </div>
  <br>    

app/views/leave_requests/new.html.erb
<h3 class="section-title text-center m-5">New Leave Request</h3>

<%= render 'form', leave_request: @leave_request %>

app/views/leave_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commence:</strong>
  <%= @leave_request.commence %>
</p>

<p>
  <strong>End:</strong>
  <%= @leave_request.end_date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @leave_request.reason %>
</p>

<p>
  <strong>Status:</strong>
  <%= @leave_request.approved %>
</p>

<%= link_to 'Edit', edit_leave_request_path(@leave_request) %> |
<%= link_to 'Back', leave_requests_path %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" role='alert'>
      <button class="close" data-dismiss="alert">×</button>
      <span class="glyphicon <%= bootstrap_glyphs_icon(type)%>" aria-hidden="true"></span>
      <span class="sr-only"><%= type.capitalize%>:</span>
      <%= message %>
    </div>
<% end %>